class Colors:
    # Shared colors used across all themes
    BLACK = "#000000"
    WHITE = "#ffffff"
    OFF_WHITE = "#F4F3F2"
    SUPER_LIGHT_GREY = "#e0e0e0"
    SUPER_LIGHT_GREY_PRESSED = "#c2c2c2"
    
    # Red button colors (for delete buttons)
    RED = "#FF0000"
    RED_BUTTON_HOVER = "#CC0000"
    RED_BUTTON_PRESSED = "#990000"
    
    # Default theme colors
    DEFAULT_BACKGROUND = "#1e1e2f"
    DEFAULT_BACKGROUND_BUTTON = "#31314d"
    DEFAULT_TEXT = "#ffffff"
    DEFAULT_INPUT_BG = "#31314d"
    DEFAULT_INPUT_TEXT = "#ffffff"
    DEFAULT_CARD_BG = "#31314d"
    DEFAULT_PRESSED_CARD_BG = "#26263b"
    DEFAULT_ACCENT = "#8ACE00"
    DEFAULT_ACCENT_HOVER = "#6DA400"
    DEFAULT_ACCENT_PRESSED = "#3C5902"
    
    # Legacy names (for backward compatibility)
    DARK_GREY = DEFAULT_BACKGROUND
    LIGHT_GREY = DEFAULT_BACKGROUND_BUTTON
    LIGHT_GREY_PRESSED = DEFAULT_PRESSED_CARD_BG
    BRAT_GREEN = DEFAULT_ACCENT
    BRAT_GREEN_BUTTON_HOVER = DEFAULT_ACCENT_HOVER
    BRAT_GREEN_BUTTON_PRESSED = DEFAULT_ACCENT_PRESSED
    
    # Red theme colors 
    RED_THEME_BACKGROUND = "#1a0a0a"
    RED_THEME_BACKGROUND_BUTTON = "#3d1f1f"
    RED_THEME_TEXT = "#ffffff"
    RED_THEME_INPUT_BG = "#3d1f1f"
    RED_THEME_INPUT_TEXT = "#ffffff"
    RED_THEME_CARD_BG = "#3d1f1f"
    RED_THEME_PRESSED_CARD_BG = "#2d0f0f"
    RED_THEME_ACCENT = "#FF6B6B"
    RED_THEME_ACCENT_HOVER = "#FF5252"
    RED_THEME_ACCENT_PRESSED = "#D32F2F"
    
    # Green theme colors 
    GREEN_THEME_BACKGROUND = "#0f1a0f"
    GREEN_THEME_BACKGROUND_BUTTON = "#2a3a2a"
    GREEN_THEME_TEXT = "#ffffff"
    GREEN_THEME_INPUT_BG = "#2a3a2a"
    GREEN_THEME_INPUT_TEXT = "#ffffff"
    GREEN_THEME_CARD_BG = "#2a3a2a"
    GREEN_THEME_PRESSED_CARD_BG = "#1f2f1f"
    GREEN_THEME_ACCENT = "#87C38F"
    GREEN_THEME_ACCENT_HOVER = "#6BA775"
    GREEN_THEME_ACCENT_PRESSED = "#4A7C59"
    
    # Blue theme colors 
    BLUE_THEME_BACKGROUND = "#0a0f1a"
    BLUE_THEME_BACKGROUND_BUTTON = "#1a1f2d"
    BLUE_THEME_TEXT = "#ffffff"
    BLUE_THEME_INPUT_BG = "#1a1f2d"
    BLUE_THEME_INPUT_TEXT = "#ffffff"
    BLUE_THEME_CARD_BG = "#1a1f2d"
    BLUE_THEME_PRESSED_CARD_BG = "#0f141f"
    BLUE_THEME_ACCENT = "#6B9BD2"
    BLUE_THEME_ACCENT_HOVER = "#5A8BC2"
    BLUE_THEME_ACCENT_PRESSED = "#4A7BB2"
    
    # Purple theme colors 
    PURPLE_THEME_BACKGROUND = "#1a0f1a"
    PURPLE_THEME_BACKGROUND_BUTTON = "#2d1f2d"
    PURPLE_THEME_TEXT = "#ffffff"
    PURPLE_THEME_INPUT_BG = "#2d1f2d"
    PURPLE_THEME_INPUT_TEXT = "#ffffff"
    PURPLE_THEME_CARD_BG = "#2d1f2d"
    PURPLE_THEME_PRESSED_CARD_BG = "#1f1420"
    PURPLE_THEME_ACCENT = "#C77DFF"
    PURPLE_THEME_ACCENT_HOVER = "#B266FF"
    PURPLE_THEME_ACCENT_PRESSED = "#9D4EDD"
